characters = [

  {
    "id": 1,
    "name": "Jon Snow",
    "house": "Stark",
    "animal": "Direwolf",
    "symbol": "Wolf",
    "nickname": "King in the North",
    "role": "King",
    "age": 25,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 2,
    "name": "Daenerys Targaryen",
    "house": "Targaryen",
    "animal": "Dragon",
    "symbol": "Dragon",
    "nickname": "Mother of Dragons",
    "role": "Queen",
    "age": 24,
    "death": 8,
    "strength": "Cunning"
  },
  {
    "id": 3,
    "name": "Tyrion Lannister",
    "house": "Lannister",
    "animal": None,
    "symbol": "Lion",
    "nickname": "The Imp",
    "role": "Hand of the King",
    "age": 39,
    "death": None,
    "strength": "Intelligence"
  },
  {
    "id": 4,
    "name": "Arya Stark",
    "house": "Stark",
    "animal": "Direwolf",
    "symbol": "Wolf",
    "nickname": "No One",
    "role": "Assassin",
    "age": 18,
    "death": None,
    "strength": "Cunning"
  },
  {
    "id": 5,
    "name": "Cersei Lannister",
    "house": "Lannister",
    "animal": None,
    "symbol": "Lion",
    "nickname": "Queen of the Seven Kingdoms",
    "role": "Queen",
    "age": 42,
    "death": 8,
    "strength": "Cunning"
  },
  {
    "id": 6,
    "name": "Sansa Stark",
    "house": "Stark",
    "animal": "Direwolf",
    "symbol": "Wolf",
    "nickname": "Lady of Winterfell",
    "role": "Queen in the North",
    "age": 22,
    "death": None,
    "strength": "Intelligence"
  },
  {
    "id": 7,
    "name": "Jaime Lannister",
    "house": "Lannister",
    "animal": None,
    "symbol": "Lion",
    "nickname": "Kingslayer",
    "role": "Knight",
    "age": 43,
    "death": 8,
    "strength": "Physically strong"
  },
  {
    "id": 8,
    "name": "Bran Stark",
    "house": "Stark",
    "animal": "Raven",
    "symbol": "Three-Eyed Raven",
    "nickname": "Bran the Broken",
    "role": "King",
    "age": 18,
    "death": None,
    "strength": "Intelligence"
  },
  {
    "id": 9,
    "name": "Theon Greyjoy",
    "house": "Greyjoy",
    "animal": None,
    "symbol": "Kraken",
    "nickname": "Reek",
    "role": "Prince",
    "age": 26,
    "death": 8,
    "strength": "Physically strong"
  },
  {
    "id": 10,
    "name": "Jorah Mormont",
    "house": "Mormont",
    "animal": None,
    "symbol": "Bear",
    "nickname": "Friendzone Knight",
    "role": "Knight",
    "age": 45,
    "death": 8,
    "strength": "Physically strong"
  },
  {
    "id": 11,
    "name": "Sandor Clegane",
    "house": "Clegane",
    "animal": None,
    "symbol": "Hound",
    "nickname": "The Hound",
    "role": "Bodyguard",
    "age": 40,
    "death": 8,
    "strength": "Physically strong"
  },
  {
    "id": 12,
    "name": "Petyr Baelish",
    "house": None,
    "animal": None,
    "symbol": "Mockingbird",
    "nickname": "Littlefinger",
    "role": "Master of Coin",
    "age": 45,
    "death": 7,
    "strength": "Cunning"
  },
  {
    "id": 13,
    "name": "Brienne of Tarth",
    "house": "Tarth",
    "animal": None,
    "symbol": "Blue Sapphire",
    "nickname": "Brienne the Beauty",
    "role": "Knight",
    "age": 32,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 14,
    "name": "Samwell Tarly",
    "house": "Tarly",
    "animal": None,
    "symbol": "Striding Huntsman",
    "nickname": "Sam",
    "role": "Maester",
    "age": 26,
    "death": None,
    "strength": "Intelligence"
  },
  {
    "id": 15,
    "name": "Varys",
    "house": None,
    "animal": None,
    "symbol": "Spider",
    "nickname": "The Spider",
    "role": "Master of Whisperers",
    "age": 50,
    "death": 8,
    "strength": "Cunning"
  },
  {
    "id": 16,
    "name": "Bronn",
    "house": None,
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Mercenary",
    "age": 35,
    "death": None,
    "strength": "Cunning"
  },
  {
    "id": 17,
    "name": "Joffrey Baratheon",
    "house": "Baratheon",
    "animal": "Stag",
    "symbol": "Crowned Stag",
    "nickname": "King Joffrey",
    "role": "King",
    "age": 19,
    "death": 4,
    "strength": "Cunning"
  },
  {
    "id": 18,
    "name": "Stannis Baratheon",
    "house": "Baratheon",
    "animal": "Stag",
    "symbol": "Crowned Stag",
    "nickname": "The King in the Narrow Sea",
    "role": "King",
    "age": 42,
    "death": 5,
    "strength": "Cunning"
  },
  {
    "id": 19,
    "name": "Melisandre",
    "house": None,
    "animal": None,
    "symbol": "Fire",
    "nickname": "The Red Woman",
    "role": "Priestess",
    "age": None,
    "death": 8,
    "strength": "Intelligence"
  },
  {
    "id": 20,
    "name": "Gendry",
    "house": None,
    "animal": None,
    "symbol": "Hammer",
    "nickname": None,
    "role": "Blacksmith",
    "age": 25,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 21,
    "name": "Robb Stark",
    "house": "Stark",
    "animal": "Direwolf",
    "symbol": "Wolf",
    "nickname": "The Young Wolf",
    "role": "King in the North",
    "age": 21,
    "death": 3,
    "strength": "Physically strong"
  },
  {
    "id": 22,
    "name": "Eddard Stark",
    "house": "Stark",
    "animal": "Direwolf",
    "symbol": "Wolf",
    "nickname": "Ned",
    "role": "Warden of the North",
    "age": 41,
    "death": 1,
    "strength": "Intelligence"
  },
  {
    "id": 23,
    "name": "Renly Baratheon",
    "house": "Baratheon",
    "animal": "Stag",
    "symbol": "Crowned Stag",
    "nickname": None,
    "role": "King",
    "age": 27,
    "death": 2,
    "strength": "Cunning"
  },
  {
    "id": 24,
    "name": "Tormund Giantsbane",
    "house": "Free Folk",
    "animal": None,
    "symbol": None,
    "nickname": "Giantsbane",
    "role": "Warrior",
    "age": 40,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 25,
    "name": "Ygritte",
    "house": "Free Folk",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Archer",
    "age": 23,
    "death": 4,
    "strength": "Cunning"
  },
  {
    "id": 26,
    "name": "Daario Naharis",
    "house": "Stormcrows",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Mercenary",
    "age": 32,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 27,
    "name": "Khal Drogo",
    "house": "Dothraki",
    "animal": None,
    "symbol": "Horse",
    "nickname": "The Great Khal",
    "role": "Khal",
    "age": 30,
    "death": 1,
    "strength": "Physically strong"
  },
  {
    "id": 28,
    "name": "Missandei",
    "house": None,
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Advisor",
    "age": 30,
    "death": 8,
    "strength": "Intelligence"
  },
  {
    "id": 29,
    "name": "Grey Worm",
    "house": "Unsullied",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Commander",
    "age": 32,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 30,
    "name": "Margaery Tyrell",
    "house": "Tyrell",
    "animal": None,
    "symbol": "Rose",
    "nickname": None,
    "role": "Queen",
    "age": 25,
    "death": 6,
    "strength": "Cunning"
  },
  {
    "id": 31,
    "name": "Oberyn Martell",
    "house": "Martell",
    "animal": "Viper",
    "symbol": "Spear",
    "nickname": "The Red Viper",
    "role": "Prince",
    "age": 42,
    "death": 4,
    "strength": "Physically strong"
  },
  {
    "id": 32,
    "name": "Ellaria Sand",
    "house": "Sand",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Paramour",
    "age": 38,
    "death": 7,
    "strength": "Cunning"
  },
  {
    "id": 33,
    "name": "Ramsay Bolton",
    "house": "Bolton",
    "animal": None,
    "symbol": "Flayed Man",
    "nickname": "The Bastard of Bolton",
    "role": "Lord",
    "age": 24,
    "death": 6,
    "strength": "Cunning"
  },
  {
    "id": 34,
    "name": "Roose Bolton",
    "house": "Bolton",
    "animal": None,
    "symbol": "Flayed Man",
    "nickname": None,
    "role": "Lord",
    "age": 50,
    "death": 6,
    "strength": "Cunning"
  },
  {
    "id": 35,
    "name": "Balon Greyjoy",
    "house": "Greyjoy",
    "animal": "Kraken",
    "symbol": "Kraken",
    "nickname": "King of the Iron Islands",
    "role": "King",
    "age": 60,
    "death": 6,
    "strength": "Cunning"
  },
  {
    "id": 36,
    "name": "Yara Greyjoy",
    "house": "Greyjoy",
    "animal": "Kraken",
    "symbol": "Kraken",
    "nickname": None,
    "role": "Captain",
    "age": 29,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 37,
    "name": "Hodor",
    "house": "Stark",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Servant",
    "age": 30,
    "death": 6,
    "strength": "Physically strong"
  },
  {
    "id": 38,
    "name": "Gilly",
    "house": None,
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Mother",
    "age": 20,
    "death": None,
    "strength": "Cunning"
  },
  {
    "id": 39,
    "name": "Meera Reed",
    "house": "Reed",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Warrior",
    "age": 19,
    "death": None,
    "strength": "Physically strong"
  },
  {
    "id": 40,
    "name": "Euron Greyjoy",
    "house": "Greyjoy",
    "animal": "Kraken",
    "symbol": "Kraken",
    "nickname": "Crow's Eye",
    "role": "King",
    "age": 40,
    "death": 8,
    "strength": "Cunning"
  },
  {
    "id": 41,
    "name": "Jojen Reed",
    "house": "Reed",
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Seer",
    "age": 13,
    "death": 4,
    "strength": "Intelligence"
  },
  {
    "id": 42,
    "name": "Mace Tyrell",
    "house": "Tyrell",
    "animal": None,
    "symbol": "Rose",
    "nickname": None,
    "role": "Lord of Highgarden",
    "age": 55,
    "death": 6,
    "strength": "Cunning"
  },
  {
    "id": 43,
    "name": "Tommen Baratheon",
    "house": "Baratheon",
    "animal": "Stag",
    "symbol": "Crowned Stag",
    "nickname": None,
    "role": "King",
    "age": 14,
    "death": 6,
    "strength": "Physically strong"
  },
  {
    "id": 44,
    "name": "Myrcella Baratheon",
    "house": "Baratheon",
    "animal": "Stag",
    "symbol": "Crowned Stag",
    "nickname": None,
    "role": "Princess",
    "age": 16,
    "death": 5,
    "strength": "Cunning"
  },
  {
    "id": 45,
    "name": "Tywin Lannister",
    "house": "Lannister",
    "animal": "Lion",
    "symbol": "Lion",
    "nickname": None,
    "role": "Hand of the King",
    "age": 67,
    "death": 4,
    "strength": "Cunning"
  },
  {
    "id": 46,
    "name": "Shae",
    "house": None,
    "animal": None,
    "symbol": None,
    "nickname": None,
    "role": "Handmaiden",
    "age": 25,
    "death": 4,
    "strength": "Cunning"
  },
  {
    "id": 47,
    "name": "High Sparrow",
    "house": None,
    "animal": None,
    "symbol": "Seven-Pointed Star",
    "nickname": None,
    "role": "High Septon",
    "age": 60,
    "death": 6,
    "strength": "Intelligence"
  },
  {
    "id": 48,
    "name": "Barristan Selmy",
    "house": None,
    "animal": None,
    "symbol": None,
    "nickname": "Barristan the Bold",
    "role": "Lord Commander",
    "age": 61,
    "death": 5,
    "strength": "Physically strong"
  },
  {
    "id": 49,
    "name": "Podrick Payne",
    "house": "Payne",
    "animal": None,
    "symbol": None,
    "nickname": "Pod",
    "role": "Squire",
    "age": 20,
    "death": None,
    "strength": "Loyalty"
  },
  {
    "id": 50,
    "name": "Olenna Tyrell",
    "house": "Tyrell",
    "animal": None,
    "symbol": "Rose",
    "nickname": "Queen of Thorns",
    "role": "Matriarch",
    "age": 70,
    "death": 7,
    "strength": "Cunning"
  }
]